.separator "	"
.output "EXULANS.filter.vcf"
SELECT EXULANS.CHROMOSOME, EXULANS.POSITION, ".", REFERENCE, ALTERNATIVE, QUALITY, ".", "DP="||COVERAGE, "GT:PL", GENOTYPE || ":" || PL, ORGANISM FROM EXULANS AS LHS WHERE EXISTS (SELECT 1 FROM FILTERED AS RHS WHERE (LHS.POSITION = RHS.position AND LHS.CHROMOSOME = RHS.chromosome));
