CREATE TABLE IF NOT EXISTS EXULANS_VALID AS
 SELECT * FROM EXULANS
 INNER JOIN FILTERED_VALIDATE_FR
  ON EXULANS.POSITION = FILTERED_VALIDATE_FR.position
  AND EXULANS.CHROMOSOME = FILTERED_VALIDATE_FR.chromosome;